############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/services"
weight = 2

[[main]]
name = "Visiting Shanghai"
url = "/visit-shanghai"
weight = 2

[[main]]
weight = 2
name = "About"
url = "/about"

[[main]]
name = "Contact"
url = "/#contact"
weight = 2


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Services"
url = "/services"
weight = 2

[[footer]]
name = "Contact"
url = "/#contact"
weight = 3
